# Generated by Django 5.1.1 on 2024-09-18 19:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_livro_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='nota',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
