# Generated by Django 3.0.7 on 2024-09-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_livro_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
