# Generated by Django 5.1.1 on 2024-09-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20240919_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='imagem',
            field=models.ImageField(default='livros/default.jpg', upload_to='livros/'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
