# Generated by Django 5.1.1 on 2024-09-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_livro_imagem_alter_livro_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='descricao',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
