# Generated by Django 5.1.1 on 2024-09-19 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_livro_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='descricao',
            new_name='descrição',
        ),
    ]
